# Generated by Django 2.0.8 on 2018-10-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=250)),
                ('image_type', models.CharField(max_length=250)),
                ('image_logo', models.ImageField(upload_to='')),
            ],
        ),
    ]
